# Type stub for the embedded `dolphin.gui` module.
# Documents the retained-mode widget API. Colors are ARGB ints (0xAARRGGBB);
# alpha is honored on the overlay path (transparency) and as rgba() alpha in QSS.

from typing import List, Optional, Sequence, Tuple

# --- immediate-mode overlay drawing (rendered in the game viewport) ---

def add_osd_message(message: str, duration_ms: int = 2000, color_argb: int = 0xFFFFFF30) -> None: ...
def clear_osd_messages() -> None: ...
def get_display_size() -> Tuple[float, float]: ...
def draw_line(a: Tuple[float, float], b: Tuple[float, float], color: int, thickness: float = 1) -> None: ...
def draw_rect(a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0, thickness: float = 1) -> None: ...
def draw_rect_filled(a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0) -> None: ...
def draw_quad(a, b, c, d, color: int, thickness: float = 1) -> None: ...
def draw_quad_filled(a, b, c, d, color: int) -> None: ...
def draw_triangle(a, b, c, color: int, thickness: float = 1) -> None: ...
def draw_triangle_filled(a, b, c, color: int) -> None: ...
def draw_circle(center: Tuple[float, float], radius: float, color: int, num_segments: Optional[int] = None, thickness: float = 1) -> None: ...
def draw_circle_filled(center: Tuple[float, float], radius: float, color: int, num_segments: Optional[int] = None) -> None: ...
def draw_text(pos: Tuple[float, float], color: int, text: str) -> None: ...
def draw_polyline(points: List[Tuple[float, float]], color: int, closed: bool = False, thickness: float = 1) -> None: ...
def draw_convex_poly_filled(points: List[Tuple[float, float]], color: int) -> None: ...

# --- retained-mode widgets ---
#
# Widgets are declared once at script start; their state is read every frame.
# Two container kinds:
#   gui.overlay(title) -> Overlay   ImGui panel drawn inside the game viewport.
#   gui.window(title)  -> Window    floating Qt OS window on the desktop.
# Styling is creation-time only. The overlay takes simplified bg_color/text_color
# (no QSS); the window takes full raw QSS via style= plus convenience colors.

class Button:
    visible: bool  # default True; False hides the widget (and its caption) until re-shown
    @property
    def clicked(self) -> bool: ...  # True once per click; reading consumes it

class SliderFloat:
    visible: bool
    # Read (live, follows the handle) / write. A write is honored as the INITIAL handle
    # position when the widget is built -- set it right after creation to choose where the
    # handle starts (e.g. value = 0.0 to center a bipolar -x..+x slider). Later writes
    # update the model but do NOT move the handle (no per-frame slider sync). Right-click
    # the slider to recenter it to the midpoint of its range.
    value: float

class Text:
    visible: bool
    def set(self, text: str) -> None: ...

class Checkbox:
    visible: bool
    # Read/write. A write is reflected on the widget each frame, so a script can drive the
    # box programmatically -- e.g. force one off to keep two checkboxes mutually exclusive.
    checked: bool

class InputText:
    visible: bool
    value: str

class Overlay:
    """In-viewport ImGui panel. Per-widget bg_color/text_color only (no QSS)."""
    def canvas(self, width: int, height: int) -> "Canvas": ...  # drawing surface above this panel's widgets
    def button(self, label: str, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Button: ...
    def slider_float(self, label: str, min: float = 0.0, max: float = 1.0, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> SliderFloat: ...
    def text(self, text: str = "", *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Text: ...
    def checkbox(self, label: str, checked: bool = False, *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> Checkbox: ...
    def input_text(self, label: str, initial: str = "", *, text_color: Optional[int] = None, bg_color: Optional[int] = None) -> InputText: ...

class Window:
    """Floating Qt OS window. Full QSS via style=; raw style wins over the
    generated color fragment on conflict."""
    def canvas(self, width: int, height: int) -> "Canvas": ...  # drawing surface above this window's widgets
    def enable_hardware_canvas(self) -> None: ...
    def button(self, label: str, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None, group: Optional[str] = None) -> Button: ...
    def slider_float(self, label: str, min: float = 0.0, max: float = 1.0, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None, group: Optional[str] = None) -> SliderFloat: ...
    def text(self, text: str = "", *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None, group: Optional[str] = None) -> Text: ...
    def checkbox(self, label: str, checked: bool = False, *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None, group: Optional[str] = None) -> Checkbox: ...
    def input_text(self, label: str, initial: str = "", *, style: Optional[str] = None, text_color: Optional[int] = None, bg_color: Optional[int] = None, group: Optional[str] = None) -> InputText: ...

def overlay(title: str, *, bg_color: Optional[int] = None, text_color: Optional[int] = None) -> Overlay: ...
def window(title: str, *, style: Optional[str] = None, bg_color: Optional[int] = None, text_color: Optional[int] = None) -> Window: ...

# --- freeform canvas ---
#
# A window backed by a replayable primitive list instead of widgets. Push primitives each frame,
# then commit() to make them visible. Points/sizes are (x, y) pixel tuples; colors are ARGB ints.
# embedded=True draws in the game viewport via ImGui; otherwise it's a floating Qt window.
# overlay=True makes that window frameless and stays-on-top. Image draws need the Qt path (not embedded).
# A Window may additionally call enable_hardware_canvas(), which makes its Canvas use the native
# mesh renderer. Hardware canvases use Direct3D 11 on Windows and Qt OpenGL on other platforms.
# They accept retained world-space mesh groups plus a script-owned screen-space HardwareHud.

class HardwareHud:
    """A retained HUD draw list for a hardware Canvas.

    Coordinates are logical canvas pixels with a top-left origin; text positions
    identify the top-left of the text box. Submit commands in desired painter order,
    then call commit() once to atomically replace the visible HUD. Colors are ARGB.
    """
    def line(self, a: Tuple[float, float], b: Tuple[float, float], color: int, thickness: float = 1.0) -> "HardwareHud": ...
    def rect(self, a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0.0, thickness: float = 1.0) -> "HardwareHud": ...
    def rect_filled(self, a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0.0) -> "HardwareHud": ...
    def circle(self, center: Tuple[float, float], radius: float, color: int, thickness: float = 1.0) -> "HardwareHud": ...
    def circle_filled(self, center: Tuple[float, float], radius: float, color: int) -> "HardwareHud": ...
    def triangle(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], color: int, thickness: float = 1.0) -> "HardwareHud": ...
    def triangle_filled(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], color: int) -> "HardwareHud": ...
    def text(self, pos: Tuple[float, float], color: int, text: str) -> "HardwareHud": ...
    def commit(self) -> None: ...

class Canvas:
    width: int
    height: int
    def clear(self) -> None: ...
    def commit(self) -> None: ...
    def line(self, a: Tuple[float, float], b: Tuple[float, float], color: int, thickness: float = 1) -> None: ...
    def rect(self, a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0, thickness: float = 1) -> None: ...
    def rect_filled(self, a: Tuple[float, float], b: Tuple[float, float], color: int, rounding: float = 0) -> None: ...
    def circle(self, center: Tuple[float, float], radius: float, color: int, thickness: float = 1) -> None: ...
    def circle_filled(self, center: Tuple[float, float], radius: float, color: int) -> None: ...
    def triangle(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], color: int, thickness: float = 1) -> None: ...
    def triangle_filled(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], color: int) -> None: ...
    def depth_triangle_filled(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], depths: Tuple[float, float, float], color: int) -> None: ...
    def depth_triangle_wire(self, a: Tuple[float, float], b: Tuple[float, float], c: Tuple[float, float], depths: Tuple[float, float, float], color: int, thickness: float = 1) -> None: ...
    def text(self, pos: Tuple[float, float], color: int, text: str) -> None: ...
    # tint=0 draws the texture as-is; otherwise RGB tints it and alpha scales opacity.
    # src is a normalized (x0, y0, x1, y1) crop for partial draws (e.g. analog fills).
    def image(self, path: str, pos: Tuple[float, float], size: Tuple[float, float], *, tint: int = 0, src: Tuple[float, float, float, float] = (0.0, 0.0, 1.0, 1.0)) -> None: ...
    # Pointer input (detached Qt canvas only; embedded ImGui canvases report nothing).
    # Coordinates are canvas pixels. Reads lag input by up to one Qt poll interval.
    def mouse_pos(self) -> Tuple[float, float, bool]: ...           # (x, y, inside)
    def take_click(self) -> Optional[Tuple[float, float]]: ...      # last unconsumed left-click, consumes it
    def take_right_click(self) -> Optional[Tuple[float, float]]: ... # last unconsumed right-click, consumes it
    def left_down(self) -> bool: ...
    def right_down(self) -> bool: ...
    def key_mask(self) -> int: ...  # W=1, A=2, S=4, D=8, Space=16, Shift=32
    def take_capture_toggle(self) -> bool: ...  # focused hardware canvas H key; consumes it
    def take_wheel(self) -> float: ...                              # accumulated wheel notches (+ = up), consumes
    # Hardware canvas only. positions are packed big/little-endian-independent float32 xyz bytes;
    # colors are packed ARGB u32 bytes. Groups 0-4 are depth-writing scene triangles, 5 is
    # depth-tested retained lines, 6 is above-scene triangles, 7 is a fill-only overlay layer,
    # and 8 is an always-on-top retained line list. Group 7 is depth-tested without writing depth
    # in normal mode, allowing translucent scripted volumes to reveal the scene behind them.
    # `debug_on_top`/`xray` instead renders group 7 above the scene. `overlay_opacity` controls
    # only group 7 fill. When unusued, it uses `fill_opacity` for compatibility.
    def hardware_mesh(self, group: int, positions: bytes, colors: bytes) -> None: ...
    def hardware_state(self, eye, right, up, forward, focal: float, radius: float,
                       fill_opacity: float, wire_opacity: float, filled: bool = True,
                       wireframe: bool = True, enabled: bool = True, xray: bool = False,
                       debug_on_top: bool = False, fullscreen: bool = False,
                       clean_capture: bool = False, hud_visible: bool | None = None,
                       overlay_opacity: float | None = None) -> None: ...
    def hud(self) -> HardwareHud: ...
    def hardware_hud(self, commands: Sequence[Sequence[object]]) -> None: ...
    # Compatibility helper: submits simple text commands at the top left. New scripts should use hud().
    def hardware_overlay(self, lines: Sequence[str]) -> None: ...

def canvas(title: str, width: int, height: int, *, embedded: bool = False, overlay: bool = False) -> Canvas: ...

# A window/overlay can host BOTH a canvas and form widgets: call window.canvas(w, h) to attach a
# drawing surface (it sits above the form widgets), then add buttons/sliders/etc. to the same window.
